import fs from "fs/promises";
import path from "path";
import type { ScanResult } from "../../types/scan.js";
import { getStyles } from "./styles.js";
import { getScripts } from "./scripts.js";
import { buildSeverityBars, buildModuleHeatmap } from "./charts.js";

export async function generateHtml(scanResult: ScanResult, outputDir: string): Promise<void> {
  const { meta, summary, findings, crossModuleFindings, modules } = scanResult;
  const allFindings = [...findings, ...crossModuleFindings];

  const findingsRows = allFindings
    .map((f) => `<tr data-severity="${f.severity}" data-mode="${f.mode}" data-fixable="${f.fix ? 'yes' : 'no'}">
      <td class="sev-${f.severity}">${f.severity}</td>
      <td><code>${f.file}:${f.line}</code></td>
      <td>${f.title}</td>
      <td>${f.mode}</td>
      <td>${f.confidence}</td>
      <td>${f.fix ? "Yes" : "No"}</td>
    </tr>
    <tr class="detail-row hidden"><td colspan="6"><pre>${f.evidence}</pre><p>${f.description}</p>${f.fix ? `<pre class="diff">- ${f.fix.diff.map((d) => d.oldCode).join("\n- ")}\n+ ${f.fix.diff.map((d) => d.newCode).join("\n+ ")}</pre>` : ""}</td></tr>`)
    .join("\n");

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Surgeon Audit — ${meta.project.name}</title>
<style>${getStyles()}</style>
</head>
<body>
<header>
<h1>Surgeon Audit Report</h1>
<div class="meta">
<span class="badge ${meta.scope}">${meta.scope === "branch" ? "Branch Scan" : "Full Scan"}</span>
<span>Health: <strong>${summary.healthScore}/100</strong></span>
<span>${meta.timestamp}</span>
</div>
</header>
<section id="summary">
${buildSeverityBars(summary.bySeverity)}
<p>Total: ${summary.totalFindings} | Fixable: ${summary.fixable} | Auto-fixable: ${summary.autoFixable}</p>
</section>
<section id="findings">
<div class="toolbar">
<input type="text" id="search" placeholder="Search findings..." />
<select id="sev-filter"><option value="">All Severities</option><option>critical</option><option>high</option><option>medium</option><option>low</option></select>
<select id="mode-filter"><option value="">All Modes</option><option>security</option><option>performance</option><option>reliability</option><option>maintainability</option><option>tests</option></select>
</div>
<table id="findings-table">
<thead><tr><th>Severity</th><th>File</th><th>Issue</th><th>Mode</th><th>Confidence</th><th>Fix</th></tr></thead>
<tbody>${findingsRows}</tbody>
</table>
</section>
<section id="modules">
<h2>Module Health</h2>
${buildModuleHeatmap(modules)}
</section>
<footer><p>Generated by surgeon-ai v${meta.version ?? "0.1.0"}</p></footer>
<script>${getScripts()}</script>
</body>
</html>`;

  await fs.writeFile(path.join(outputDir, "audit.html"), html, "utf-8");
}
